version: 2
jobs:
  build:
    working_directory: ~/tstt
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - restore_cache:
          name: Restore dtslint cache
          key: dtslint-cache
      - run:
          name: Test with coverage
          command: yarn test --ci --coverage --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "coverage/junit/junit.xml"
      - save_cache:
          name: Save dtslint cache
          key: dtslint-cache
          paths:
            - ~/.dts
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage/junit
